### ISSUE TITLE
Task __init__ expects bytes for cdb but it should be bytearray

### ISSUE THREAD

**Issue by rosjat** [python-scsi/cython-iscsi#3]
by trying to fix up pyiscsi/ISCSIDevice i came to a halt at creating a Task with the following error

```
ython examples/reportluns.py 'iscsi://127.0.0.1/iqn.2019-12.local.mr:virtual-dvd:mu-fedora32/0'
Traceback (most recent call last):
  File "examples/reportluns.py", line 23, in <module>
    main(init_device(sys.argv[1]))
  File "examples/reportluns.py", line 14, in main
    with SCSI(device) as s:
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 64, in __init__
    self.__init_opcode()
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 92, in __init_opcode
    self.device.devicetype = self.inquiry().result['peripheral_device_type']
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 197, in inquiry
    self.execute(cmd)
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 113, in execute
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 111, in execute
    self.device.execute(cmd)
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyiscsi/iscsi_device.py", line 115, in execute
    task = iscsi.Task(cmd.cdb, dir, xferlen)
TypeError: Argument 'cdb' has incorrect type (expected bytes, got bytearray)

```
that is correct since Task class __init__ is defined as followed ...
```

    def __init__(self, bytes cdb, scsi_xfer_dir direction, size_t xferlen):
        self._task = scsi_create_task(len(cdb), cdb, direction, xferlen)
        self._has_datain = False
        self._has_dataout = False
```
but it should be 

```
    def __init__(self, bytearray cdb, scsi_xfer_dir direction, size_t xferlen):
        self._task = scsi_create_task(len(cdb), cdb, direction, xferlen)
        self._has_datain = False
        self._has_dataout = False
```
if this is possible in cython syntax

**Comment by Flameeyes** [comment]
This is interesting. I expected Cython's `bytes` to work with `bytearray` input, since `bytearray` is a strict super-set.

Changing the `__init__` to take `bytearray` would preclude using `bytes` for it, because Cython's `bytearray` is mutable (which is correct for the data in/out interfaces, but not what I would expect for `cdb`, which is a constant).

I guess I can fix this in python-scsi by using `iscsi.Task(bytes(cmd.cdb), dir, xferlen)` — and maybe figure out if a bug report to Cython is worth it.

**Comment by Flameeyes** [comment]
Filed issue as https://github.com/cython/cython/issues/3488

**Comment by Flameeyes** [comment]
Added workaround for the issue (and a reference to it.)

**Comment by rosjat** [comment]
workaround seems to work for Task __init__ but then Context class command method fails

```
Traceback (most recent call last):
  File "examples/reportluns.py", line 23, in <module>
    main(init_device(sys.argv[1]))
  File "examples/reportluns.py", line 14, in main
    with SCSI(device) as s:
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 64, in __init__
    self.__init_opcode()
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 92, in __init_opcode
    self.device.devicetype = self.inquiry().result['peripheral_device_type']
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 197, in inquiry
    self.execute(cmd)
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 113, in execute
    raise e
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyscsi/scsi.py", line 111, in execute
    self.device.execute(cmd)
  File "/usr/local/lib/python3.7/site-packages/pyscsi/pyiscsi/iscsi_device.py", line 120, in execute
    cmd.datain)
SystemError: <method 'command' of 'iscsi.Context' objects> returned NULL without setting an error

```
could be my context string but thats hard to tell from this traceback. Here my target output from tgtadm 

```
sudo tgtadm --lld iscsi --mode target --op show
Target 1: iqn.2019-12.local.mr:virtual-dvd:mu-fedora32
    System information:
        Driver: iscsi
        State: ready
    I_T nexus information:
        I_T nexus: 2
            Initiator: iqn.1994-05.com.redhat:a048115b3c7e alias: localhost.localdomain
            Connection: 0
                IP Address: 127.0.0.1
    LUN information:
        LUN: 0
            Type: controller
            SCSI ID: IET     00010000
            SCSI SN: beaf10
            Size: 0 MB, Block size: 1
            Online: Yes
            Removable media: No
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: null
            Backing store path: None
            Backing store flags: 
        LUN: 1
            Type: cd/dvd
            SCSI ID: IET     00010001
            SCSI SN: STGTDVD01
            Size: 0 MB, Block size: 1
            Online: No
            Removable media: Yes
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: mmc
            Backing store path: None
            Backing store flags: 
        LUN: 2
            Type: changer
            SCSI ID: IET     00010002
            SCSI SN: XYZZY_0
            Size: 0 MB, Block size: 1
            Online: Yes
            Removable media: Yes
            Prevent removal: No
            Readonly: No
            SWP: No
            Thin-provisioning: No
            Backing store type: smc
            Backing store path: /root/tgt/smc
            Backing store flags: 
    Account information:
    ACL information:
        ALL


```
but then again at this point we are connected to the target and just issue the task and the scsi command to the context so it should return something at all

**Comment by rosjat** [comment]
nah this doesnt cause it i had that fixed already, the error is still there sorry forget to mention this before. We still got the NULL

**Comment by Flameeyes** [comment]
Yeah I'm debugging that right now. The NULL is returned by the C extension, but it shouldn't ever happen, as the generated code should only jump to the NULL codepath when there's an error set.

**Comment by rosjat** [comment]
well believe me thats why i gave up on a c module and just took the SWIG version. SWIG does total wierd stuff that at some point was just not really debugable to make it a simple c extention. I think I also faild at the task stuff

**Comment by Flameeyes** [comment]
Yeah in this case Cython wasn't wrong, I just completely missed that some of the interfaces need to be error-checked, so I was skimping on the checking.

The error message could be better, for sure.
